# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MDU2MWRkZGM3ZGIxYzVlYWFjMWE1ZjM1NDUxMDQ4MzI0MjUwNWE2ZDk0NTA5NTAyNjEzNzcyOWFmMDc1YzhhNWQ4YTM2YzA1Njk4MGFlOGMzNDMxMjI4MmU5OTgzNmI2MjFjYWVmYjMyOWNmNmYxZTQwNGQzNjc4NjQ3OTllZmE=
